#!/bin/bash

	BADVPN="/home/BadVPN"
	UDP="/bin/badudp"
	if [ -f "$UDP" ]; then
		echo "BADVPN STATUS: INSTALADO!"
		sleep 3
		badvpnmenu
		exit
	else
		echo "ATUALIZANDO REPOSITÓRIOS..."
		apt-get update 1> /dev/null 2> /dev/null
		apt-get upgrade -y 1> /dev/null 2> /dev/null
		echo "AGUARDE UM INSTANTE..."
		apt-get install build-essential -y 1> /dev/null 2> /dev/null
  	apt-get install gcc -y 1> /dev/null 2> /dev/null
  	apt-get install g++ -y 1> /dev/null 2> /dev/null
  	apt-get install make -y 1> /dev/null 2> /dev/null
  	echo "SÓ MAIS UM INSTANTE..."
  	mkdir $BADVPN
  	cd $BADVPN
		wget -q --no-check-certificate http://www.cmake.org/files/v2.8/cmake-2.8.12.tar.gz 1> /dev/null 2> /dev/null 
  	wget -q --no-check-certificate https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/badvpn/badvpn-1.999.128.tar.bz2 1> /dev/null 2> /dev/null 
  	tar xvzf cmake-2.8.12.tar.gz 1> /dev/null 2> /dev/null 
  	tar xf badvpn-1.999.128.tar.bz2 1> /dev/null 2> /dev/null
  	echo "INSTALANDO RECURSOS..."
  	cd $BADVPN/cmake-2.8.12
  	./bootstrap --prefix=/usr 1> /dev/null 2> /dev/null
  	make 1> /dev/null 2> /dev/null 
  	make install 1> /dev/null 2> /dev/null 
  	cd $BADVPN/badvpn-1.999.128
  	cmake -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 1> /dev/null 2> /dev/null
  	make install 1> /dev/null 2> /dev/null
  	echo "CONFIGURANDO..."
  	echo "#!/bin/bash
  	badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 512 --max-connections-for-client 8" > $UDP
  	chmod a+x $UDP
  	echo "BADUDP INSTALADO COM SUCESSO!!!"
  	fi
echo -e "APERTE A TECLA ENTER PARA VOLTAR AO MENU..."
read ENTER
badvpnmenu
exit
