#!/bin/bash

#############################################
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
fim="\033[0;37m"
#############################################

BADVPN="/home/BadVPN"
UDP="/bin/badudp"

# menu badvpn
if [ -f "$UDP" ]; then
	clear
	echo -e $amarelo"BADVPN STATUS:"$fim $verdeClaro"INSTALADO!"$fim
	NUMBER=$(ps -x | grep -c "badvpn-udpgw")
	if [ $NUMBER = "2" ]; then
		echo -e $amarelo" STATUS:"$fim $verdeClaro" ATIVO"$fim
        echo -e $verdeClaro"=-=-=-=-=-=-=-="$fim
        echo $branco" [1] PARAR"$fim
		echo $branco" [2] DESINSTALAR"$fim
		echo $branco" [3] SAIR"$fim
        echo -e $verdeClaro"=-=-=-=-=-=-=-="$fim
		read -p "OPÇÃO [1-3]:" opcao
		case $opcao in
			1)
				clear
				pkill -f badudp
				sleep 3
				badvpnmenu
				exit
				;;
			2)
				clear
				badvpn-remove
				;;
			3)
				clear
				menu
				;;
			*)
				clear
				badvpnmenu
				exit
				;;
		esac
	else
		clear
        echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-="$fim
		echo -e $branco" STATUS:"$fim$vermelhoClaro" DESATIVADO!"$fim
		echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-="$fim
        echo -e $branco" [1] ATIVAR"$fim
		echo -e $branco" [2] DESINSTALAR"$fim
		echo -e $branco" [3] SAIR"$fim
        echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-="$fim
		read -p "OPÇÃO [1-3]:" opcao2
		case $opcao2 in

			1)
				clear
				screen -dmS screen badudp
				sleep 3
				badvpnmenu
				exit
				;;
			2)
				clear
				badvpn-remove
				;;
			3)
				clear
				menu
				;;
			*)
				clear
				badvpnmenu
				exit
				;;
		esac
	fi
	else
		clear
        echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-="$fim
		echo -e $branco"BADVPN STATUS:"$fim$vermelhoClaro" NÃO INSTALADO!"$fim
		echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-="$fim
        echo -e $branco" [1] INSTALAR"$fim
		echo -e $branco" [2] SAIR"$fim
        echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-="$fim
		read -p "OPÇÃO [1-2]:" opcao3
		case $opcao3 in
			1)
				badvpn-setup #setup badudp
				;;
			2)
				clear
				menu
				exit
				;;
			*)
				clear
				badvpnmenu #menu
				exit
				;;
		esac
fi
