#!/bin/bash

#############################################
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
fim="\033[0;37m"
#############################################

BADVPN="/home/BadVPN"
UDP="/bin/badudp"

  if [ -f "$UDP" ]; then
		clear
    echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="$fim
    echo -e $amarelo"BADVPN STATUS:"$fim $verdeClaro"INSTALADO!"$fim
		sleep 3
		badvpnmenu
		exit
	else
    clear
		echo -e $verdeClaro" ATUALIZANDO REPOSITÓRIOS..."$fim
		apt-get update 1> /dev/null 2> /dev/null
		apt-get upgrade -y 1> /dev/null 2> /dev/null
    clear
		echo -e $verdeClaro" AGUARDE UM INSTANTE..."$fim
		apt-get install build-essential -y 1> /dev/null 2> /dev/null
  	apt-get install gcc -y 1> /dev/null 2> /dev/null
  	apt-get install g++ -y 1> /dev/null 2> /dev/null
  	apt-get install make -y 1> /dev/null 2> /dev/null
  	clear
    echo -e $verdeClaro" SÓ MAIS UM POUCO..."$fim
  	mkdir $BADVPN
  	cd $BADVPN
    clear
    echo -e $verdeClaro" ISSO PODE DEMORAR MUITO... AGUARDE!..."$fim
		wget -q --no-check-certificate http://www.cmake.org/files/v2.8/cmake-2.8.12.tar.gz 1> /dev/null 2> /dev/null
  	wget -q --no-check-certificate https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/badvpn/badvpn-1.999.128.tar.bz2 1> /dev/null 2> /dev/null
  	tar xvzf cmake-2.8.12.tar.gz 1> /dev/null 2> /dev/null
  	tar xf badvpn-1.999.128.tar.bz2 1> /dev/null 2> /dev/null
  	clear
    echo -e $verdeClaro" INSTALANDO RECURSOS..."$fim
  	cd $BADVPN/cmake-2.8.12
  	./bootstrap --prefix=/usr 1> /dev/null 2> /dev/null
  	make 1> /dev/null 2> /dev/null
  	make install 1> /dev/null 2> /dev/null
  	cd $BADVPN/badvpn-1.999.128
  	cmake -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 1> /dev/null 2> /dev/null
  	make install 1> /dev/null 2> /dev/null
  	clear
    echo -e $verdeClaro" CONFIGURANDO..."$fim
  	echo "#!/bin/bash
badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 512 --max-connections-for-client 8" > $UDP
  	chmod a+x $UDP
    clear
  	echo -e $verdeClaro" BADUDP INSTALADO COM SUCESSO!!!"$fim
  	fi
echo -e $amarelo" APERTE A TECLA ENTER PARA VOLTAR AO MENU..."$fim
read ENTER
badvpnmenu
exit
