#!/bin/bash

#############################################
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
fim="\033[0;37m"
#############################################

reinstalar () {
apt-get update -y
apt-get upgrade -y
wget -c -P /bin https://raw.githubusercontent.com/Leonn34/script-2/master/setup.sh
chmod +x /bin/setup.sh
bash /bin/setup.sh
}

remove () {
echo -e ""
echo -e ""
rm /bin/criarusuario >/dev/null 2>/dev/null
rm /bin/expcleaner >/dev/null 2>/dev/null
rm /bin/sshlimiter >/dev/null 2>/dev/null
rm /bin/addhost >/dev/null 2>/dev/null
rm /bin/delhost >/dev/null 2>/dev/null
rm /bin/sshmonitor >/dev/null 2>/dev/null
rm /bin/ajuda >/dev/null 2>/dev/null
rm /bin/menu >/dev/null 2>/dev/null
rm /bin/atualizar >/dev/null 2>/dev/null
rm /bin/clearcache >/dev/null 2>/dev/null
rm /bin/badudp >/dev/null 2>/dev/null
rm /bin/userbkp >/dev/null 2>/dev/null
rm /bin/socks.py >/dev/null 2>/dev/null
rm /bin/setup.sh >/dev/null 2>/dev/null
rm /bin/att >/dev/null 2>/dev/null
rm /bin/ver >/dev/null 2>/dev/null
rm /bin/ver1 >/dev/null 2>/dev/null
rm /bin/testeconexao >/dev/null 2>/dev/null
rm /bin/speedtest.py >/dev/null 2>/dev/null
rm /bin/alterarsenha >/dev/null 2>/dev/null
rm /bin/alterarlimite >/dev/null 2>/dev/null
rm /bin/remover >/dev/null 2>/dev/null
rm /bin/socks >/dev/null 2>/dev/null

ssh="/etc/ssh/sshbak"
if [ ! -f "$ssh" ]
then
  echo ""
else
mv -f /etc/ssh/sshbak /etc/ssh/sshd_config
fi
apt-get remove squid3 -y 1>/dev/null 2>/dev/null apt-get remove squid -y 1>/dev/null 2>/dev/null apt-get autoremove -y 1>/dev/null 2>/dev/null
}
clear
echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="$fim
echo -e $vermelhoClaro" DESINSTALAR OU INSTALAR OUTRO GERENCIADOR?"$fim
echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="$fim
echo ""
echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="$fim
echo -e $amarelo" [1] DESINSTALAR"$fim
echo -e $amarelo" [2] INSTALAR OUTRO GERENCIADOR"$fim
echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="$fim
read -p ": " resposta
case $resposta in
 2)
remove
reinstalar
exit
;;
 *)
remove
exit
;;
esac
exit
