#!/bin/bash
#Criado por Elton Sousa
#Script para escolher em qual porta rodar o SOCKS

#############################################
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
fim="\033[0;37m"
#############################################

sock="/etc/checker/sock_status"

# menu socks
menusocks () {
clear
echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="$fim
echo -e $branco" MENU SOCKS"$fim
echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="$fim
ps -C "python socks.py" > /dev/null
if [ $? = 0 ]; then
echo -e $pretoCinza" STATUS:"$fim $verdeClaro"ON"$fim
echo "SOCKS" > $sock # cria o arquivo pra verificar se está ativo no menu principal
echo -e ""
echo -e $branco" [1] PARAR"$fim
echo -e $branco" [2] SAIR"$fim
echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="$fim
read -p " OPÇÃO [1-2] :" opcao
case $opcao in
1)
socks_off
exit
;;
2)
menu
exit
;;
*)
cho -e $vermelhoClaro" OPÇÃO INVÁLIDA!"$fim
sleep 3
menusocks
exit
;;
esac
else
echo -e $pretoCinza" STATUS:"$fim $vermelho"OFF"$fim
echo "" > $sock # cria o arquivo pra verificar se está ativo no menu principal
echo -e ""
echo -e $branco" [1] ATIVAR"$fim
echo -e $branco" [2] SAIR"$fim
echo -e $verdeClaro"=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="$fim
read -p " OPÇÃO [1-2] :" opcao2
case $opcao2 in
1)
socks_on # ativar
exit
;;
2)
menu
exit
;;
*)
echo -e $vermelhoClaro" OPÇÃO INVÁLIDA!"$fim
sleep 3
menusocks
exit
;;
esac
fi
}

# ativar socks
socks_on () {

p1=80
p2=8080
p3=8799
p4=3128

clear
echo " ESCOLHA EM QUAL PORTA DESEJA RODAR O SOCKS:"
echo " 80, 8080, 3128 ou 8799"
read -p " PORTA: " -e -i 80 port
echo " SUA OPÇÃO:: " $port

if [ -z $port ]; then
	echo " PRECISA ESCOLHER A PORTA!"
	sleep 3
	clear
	socks
	exit
else
	if [ $port = $p1 ]; then
		clear
		cd /bin
		screen -dmS screen python socks.py $p1
		echo " SOCKS RODANDO NA PORTA" $p1
		sleep 3
		clear
		menusocks
		exit
		fi
		if [ $port = $p2 ]; then
			clear
			cd /bin
			screen -dmS screen python socks.py $p2
			echo " SOCKS RODANDO NA PORTA" $p2
			sleep 3
			clear
			menusocks
			exit
			fi
			if [ $port = $p3 ]; then
				clear
				cd /bin
				screen -dmS screen python socks.py $p3
				echo " SOCKS RODANDO NA PORTA" $p3
				sleep 3
				clear
				menusocks
				exit
				fi
				if [ $port = $p4 ]; then
					clear
					cd /bin
					screen -dmS screen python socks.py $p4
					echo " SOCKS RODANDO NA PORTA" $p4
					sleep 3
					clear
					menusocks
					exit
					else
					echo " OPÇÃO INVÁLIDA!"
					sleep 3
					menusocks
					exit
					fi

	fi
}

socks_off () {
	pkill -f socks.py
	menusocks
}

menusocks